name = "UFFFiles"
uuid = "20c5726e-8372-4c34-be2c-190a5a70d483"
version = "1.0.1"
authors = ["Mathieu Aucejo <79322171+maucejo@users.noreply.github.com> and contributors"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Scanf = "6ef1bc8b-493b-44e1-8d40-549aa65c4b41"

[compat]
Dates = "1.11.0"
Glob = "1.3.1"
Printf = "1.11.0"
Scanf = "0.5.4"
Test = "1.11.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
